# -*- coding: utf-8 -*-
"""Lab5 Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1128h-JhCzFle4n4K1cBly67iYjjvuCzF

2.1:Concrete Compressive strength is the target other columns are features
"""

import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor

"""Importing the dataset

"""

from google.colab import drive
drive.mount("/content/gdrive")

from google.colab import files
uploaded = files.upload()

df=pd.read_csv('Concrete_Data.xls - Sheet1.csv')

"""Checking for columns with null values

"""

df.loc[:, df.isnull().any()].columns ### hence no values obtained

"""Splitting the dataset into X(input) and Y(output)

"""

X=df.iloc[:,0:8]
Y=df.iloc[:,8]

"""Regression using Mean squared Error

"""

X_train,X_test,y_train,y_test=train_test_split(X,Y,shuffle=True,test_size=0.3)
regressor=DecisionTreeRegressor(criterion='mse',splitter='random',random_state=2021)
dtr=regressor.fit(X_train,y_train)

"""Score 

"""

pred = regressor.predict(X_train)
print('Model Accuracy | ',regressor.score(X_train,y_train))

"""Graph"""

import graphviz
dot_tree = tree.export_graphviz(dtr,filled=True,rounded=True)
graph = graphviz.Source(dot_tree, format="png") 
graph

dtr.tree_.max_depth

"""Regression using Mean absolute error

"""

X_train,X_test,y_train,y_test=train_test_split(X,Y,shuffle=True,test_size=0.3)
regressor1=DecisionTreeRegressor(criterion='mae',splitter='random',random_state=2021)
dtr1=regressor1.fit(X_train,y_train)

"""Prediction and score

"""

pred = regressor.predict(X_train)
print('Model Accuracy | ',regressor.score(X_train,y_train))

import graphviz
dot_tree1 = tree.export_graphviz(dtr1,filled=True,rounded=True)
graph1 = graphviz.Source(dot_tree1, format="png") 
graph1

